project_id = "gyxspsuctbrxhwiyfvlj"

[functions.delete-file]
verify_jwt = false

[functions.delete-storage-recursive]
verify_jwt = false

[functions.generate-upload-url]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.calculate-route]
verify_jwt = false
